#!/bin/bash
cd "$( dirname "$0" )"

## su -
## systemctl disable wpa_supplicant
## vi /etc/network/interfaces
## vi /etc/wpa_supplicant/wpa_supplicant.conf
## vi /etc/udev/rules.d/70-persistent-net.rules
## ifup -a
## ip addr ls
## apt update
## apt install aptitude git ssh sudo vim net-tools
## vim /etc/group
## grep himdel /etc/sudoers || echo 'himdel ALL=NOPASSWD: ALL' >> /etc/sudoers
## vim /etc/dhcp/dhclient.conf # supersede dns

## ssh-keygen, add to github, clone doftiles
## sudoers
##   also Defaults !admin_flag

sudo dpkg --add-architecture i386
sudo apt update

sudo apt install steam:i386

sudo apt install lua5.2 luarocks lua-socket lua-xmlrpc lua-zlib mpv
sudo ln -s /usr/share/lua/5.1/xmlrpc /usr/share/lua/5.2/xmlrpc
mkdir -p ~/.config/mpv/scripts
git clone https://github.com/rumkex/osdb-mpv.git ~/.config/mpv/scripts

grep max_user_watches /etc/sysctl.conf || ( echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p )

wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
wget https://dl.google.com/linux/direct/google-chrome-beta_current_amd64.deb
sudo dpkg -i google-chrome-beta_current_amd64.deb
rm -vf google-chrome-beta_current_amd64.deb

[ -e ~/bin ] || ln -sv ~/dotfiles/bin ~/bin

cd /usr/local/bin/
sudo ln -sv ~/bin/rename.perl rename
sudo ln -sv ~/bin/xdg-open .

# TODO link home stuff

./update
