#!/bin/sh

# dependencies
sudo apt install python3 \
                 python3-pip \
                 python3-setuptools \
                 python3-wheel \
                 libpython3-dev \
                 arping \
                 libtool

# python dependencies
# https://raw.githubusercontent.com/home-assistant-libs/pytradfri/master/requirements.txt
pip-install aiocoap==0.4.7 \
            DTLSSocket==0.1.16 \
            pydantic==1.10.9
pip-install pytradfri \
            colormath

# /usr/lobcal/bin/coap-client
apt-get install -f autoconf automake libtool

git clone --depth 1 --recursive -b dtls https://github.com/home-assistant/libcoap.git
cd libcoap
./autogen.sh
./configure --disable-documentation --disable-shared --without-debug CFLAGS="-D COAP_DEBUG_FD=stderr"
make
sudo make install
cd ..
rm -rf libcoap/
