#!/bin/sh
xrandr --output eDP-1  --off \
       --output DP-2-2 --mode 1920x1080 --pos 0x0 --crtc 1 --rotate normal --primary \
       --output DP-2-1 --mode 1920x1080 --pos 1920x0 --crtc 2 --rotate normal
