#!/bin/sh
xrandr --output eDP-1  --mode 1920x1080 --pos 0x0    --crtc 0 --rotate normal --primary \
       --output DP-2-2 --mode 1920x1080 --pos 1920x0 --crtc 1 --rotate normal \
       --output DP-2-1 --mode 1920x1080 --pos 3840x0 --crtc 2 --rotate normal
