#!/bin/bash
set -x
set -e

cd ~/ui-components
[`git branch-name` != 'master'] && exit 1
git up

TAG=$(npm version patch)
git tag -d "$TAG"

VER=$(echo "$TAG" | sed 's/^v//')

echo TAG: "$TAG", VER: "$VER"
[ -z "$TAG" ] && exit 2
[ -z "$VER" ] && exit 3

bower version "$VER"
git tag -d "$TAG"

sed -i 's/^\(  "version": \)".*",$/\1"'"$VER"'",/' bower.json
EDITOR=true git commit --amend -a

git reset HEAD~2
git commit -a -m "$VER"

rm -rf node_modules
yarn

git push upstream master
npm publish

git checkout -b tmp-"$VER"

rm -rf dist
yarn run build

git add -f dist/css/ui-components.css dist/css/ui-components.css.map
git add -f dist/js/ui-components.js dist/js/ui-components.js.map
git commit -m "bower build for $TAG"

git tag "$TAG" # create the tag on the bower commit
git checkout master

git push upstream --tags
git branch -D tmp-"$VER"
